# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Elijah Andrews
url:              http://elijahandrews.com
paginate:         1
baseurl:          /
author:
  name:           Elijah Andrews

# Custom vars
version:          1.0.0

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
